/* Captions remain real, readable text rather than lettering baked into art. */
(()=>{'use strict';
const intro=[
 ['Eine Welt, die voneinander lernt','Lichtquell wuchs, weil Menschen und Wesen unterschiedliche Stärken zusammenbrachten: Wissen, Mut, Fürsorge, Bewegung, Neugier und die Fähigkeit, einander zuzuhören. Niemand musste alles können.'],
 ['Das Rauschen','Mit der Zeit wurde die Welt lauter. Nachrichten, Unterhaltung, Gerüchte, Werbung und ständige Reaktionen lagen übereinander. Nicht die Technik selbst war das Problem – sondern dass immer weniger Raum blieb, um zu prüfen, zu üben, zu erleben und auch einmal nichts zu tun.'],
 ['Eine andere Art von Stärke','Wo Aufmerksamkeit fehlt, entstehen Missverständnisse schneller. Aus Unsicherheit kann Wut werden, aus Gruppen können Lager werden. Du brichst mit deinem Begleiter auf: nicht um allen dieselbe Antwort zu geben, sondern um verstehen, handeln und gemeinsam stärker werden wieder miteinander zu verbinden.']
];
const chapters=[
 {title:'Ein Gerücht im Flüsterwald',before:'Ein kurzer Spiegelclip zeigt einen Schatten und einen umgestürzten Kräuterkorb. „Das Monster greift alle an!“, behaupten die geteilten Nachrichten. Niemand hat Nela gefragt, was davor geschah.',after:'Ihr nehmt euch Zeit. Welche Pflanzen lagen im Korb? Was hat das Wesen erschreckt? Wissen und Zuhören können aus einer Drohung eine verständliche Geschichte machen.'},
 {title:'Die Brücke der Behauptungen',before:'Ein Bild der gesperrten Brücke macht die Runde: „Jaro lässt uns absichtlich nicht hinüber!“ Auf beiden Seiten sammeln sich wütende Wesen. Der Fluss trennt sie – das Gerücht treibt sie weiter auseinander.',after:'Professor Alwins Lehre hilft: Erst ansehen, messen und rechnen. Was trägt das alte Holz noch? Wer die Ursache versteht, kann Sicherheit erklären und gemeinsam reparieren, statt einen Feind zu suchen.'},
 {title:'Mehr als ein kurzer Ausschnitt',before:'Am Spiegelsee wiederholt das Netz immer dieselben perfekten Bilder. Welle soll schneller, klüger und besser werden. Doch niemand sieht, wie erschöpft sie ist. Ein kurzer Satz wird ohne Zusammenhang weitergeschickt.',after:'Mira weiß: Lesen heißt mehr als Wörter erkennen. Ihr sucht den Zusammenhang, stellt Fragen und lasst Pausen zu. Nicht jede stille Antwort ist Ablehnung – und nicht jedes Bild erzählt die ganze Wahrheit.'},
 {title:'Die Mutprobe im Sturm',before:'Am Windpass verbreitet sich eine Mutprobe: „Wer umkehrt, ist schwach!“ Tara will mithalten. Ihr Gefährte ist müde, doch die nächste Nachricht drängt schon zum Weitergehen.',after:'Ihr vergleicht Wetterzeichen, Weglänge und Kraft. Logisches Denken hilft, Behauptungen zu prüfen. Eine begründete Pause kann mutiger sein als blindes Mitmachen.'},
 {title:'Was wir miteinander anfangen',before:'Im Morgenhain bewahrt der Hüter Erinnerungen an eine Welt, die viel wusste und immer weniger nachfragte. Aus Gerüchten wurden Lager. Aus Lagern Gegner. Wissen allein hatte nicht genügt – es wurde nicht mehr gemeinsam angewendet.',after:'Ihr bringt keine perfekte Antwort mit, sondern neue Gewohnheiten: lernen, prüfen, zuhören und teilen. Bildung macht euch stark. Nicht, um alle zu besiegen, sondern um euch nicht gegeneinander aufbringen zu lassen.'}
];
function opening(index,replay){const i=Math.max(0,Math.min(2,index||0)),f=intro[i];return `<section class="panel comic-scene"><div class="comic-intro-art" role="img" aria-label="Drei Comicbilder: gemeinsames Lernen, das wachsende Rauschen und eine bedrohte Brücke als Beginn der Reise."></div><div class="comic-copy"><div class="kicker">Knowsters · Prolog ${i+1} / 3</div><h1>${f[0]}</h1><p>${f[1]}</p><button class="primary" data-action="next-intro">${i===2?replay?'Zurück zur Reise':'Meinen Charakter erstellen':'Weiterlesen'} →</button></div></section>`;}
function transition(id){const c=chapters[id-1];return `<section class="panel comic-scene"><div class="kicker comic-kicker">Kapitel ${id} / 5 · Eine neue Welt</div><div class="comic-chapter-art comic-chapter-${id}" role="img" aria-label="${c.title}: Zwei Comicbilder zeigen den Konflikt und einen gemeinsamen Ausweg."></div><div class="comic-copy"><h1>${c.title}</h1><div class="comic-captions"><p>${c.before}</p><p>${c.after}</p></div><button class="primary" data-action="comic-continue">Diese Welt betreten →</button></div></section>`;}
window.KnowstersComics={intro,chapters,opening,transition};
})();
