/* People and conversations are the interface for houses and story encounters. */
(()=>{'use strict';
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const portrait=(id,cls='')=>`<span class="npc-portrait npc-${id} ${cls}" role="img" aria-label="${escape(window.KnowstersStory.residents[id]?.name||'Bewohner')}"></span>`;
const reply=(action,label,extra='',disabled=false)=>`<button class="dialog-reply" data-action="${action}" ${extra} ${disabled?'disabled':''}><span class="reply-mark">›</span><span>${label}</span></button>`;
function scene({npc,location,text,body='',choices='',outdoors=false,footer=''}){
 const person=window.KnowstersStory.residents[npc];
 return `<section class="conversation ${outdoors?'outdoors':''}"><div class="conversation-stage"><div class="room-location">${escape(location)}</div><div class="resident-figure">${portrait(npc,'large')}<span class="resident-badge">${escape(person.role)}</span></div></div><div class="speech-panel"><div class="speaker-name">${escape(person.name)}</div><div class="spoken-text">${text}</div>${body}<div class="dialog-choices">${choices}</div>${footer}</div></section>`;
}
function teacher({kind,petName,profile,knowledge,task,points,about=false,notice='',bondLine='',bondDelta=null,targetAttribute=null}){
 const S=window.KnowstersStory,P=window.KnowstersProgress,domain=P.domains[kind]||P.domains.math,npc=S.teachers[kind]||'guide',person=S.residents[npc],location={math:'Alwins Rechenwerkstatt',language:'Miras Bibliothek',logic:'Taras Denkturm'}[kind]||`Lichtquell · Wissenszentrum · ${domain.label}`;
 const validAttrs=P.validTrainingAttributes(kind),chosenAttr=validAttrs.includes(targetAttribute)?targetAttribute:validAttrs[0],attr=P.attributeMap[chosenAttr];
 const attrPicker=`<div class="training-target"><span>Diese Aufgabe trainiert:</span><div>${validAttrs.map(id=>`<button type="button" class="training-attribute ${id===chosenAttr?'selected':''}" data-action="training-attribute" data-id="${id}" aria-pressed="${id===chosenAttr}">${escape(P.attributeMap[id].label)}</button>`).join('')}</div><small>Das Fach bleibt dasselbe – du entscheidest, welche passende Stärke deines Wesens du entwickeln möchtest.</small></div>`;
 let text='',body=attrPicker,choices='';
 if(!task){const intro=S.teachers[kind]?(about?person.about:person.greeting):`Im Wissenszentrum kannst du ${domain.label} trainieren. Die Aufgaben starten ungefähr passend zu deinem Altersbereich und passen sich später je Fach an deine Antworten an.`;text=escape(intro)+`<p class="spoken-aside">${escape(petName)} bleibt bei dir. Wissen gehört dir – die Entwicklung daraus fließt in dein Wesen.</p>`;choices=reply('begin-task','Neue Aufgabe starten <small>1 Wissenspunkt</small>',`data-kind="${kind}"`,points<1)+(S.teachers[kind]&&!about?reply('teacher-about','„Was können wir hier lernen?“'):'')+reply('knowledge','Zum Wissensprofil');body+=(points<1?'<p class="teacher-note">Euch fehlen gerade Wissenspunkte. Im Abenteuer erhältst du neue – eine ähnliche Folgeaufgabe nach einem Fehler kostet aber keinen weiteren Punkt.</p>':'');}
 else if(!task.complete){
  text=`<p class="teacher-topic">${escape(domain.label)} · Stufe ${(task.tier??0)+1}/8 · ${escape(task.difficulty||'')}</p><div class="teacher-learning-goal"><strong>${escape(task.topic||task.label)}</strong><span>${escape(task.learningGoal||'')}</span>${task.scope?`<small>${escape(task.scope)}</small>`:''}</div><div class="spoken-question">${escape(task.prompt)}</div>`;
  if(task.fractionVisual)body+=`<div class="fraction-bar" role="img" aria-label="${task.fractionVisual.n} von ${task.fractionVisual.d} gleichen Teilen sind markiert">${Array.from({length:task.fractionVisual.d},(_,i)=>`<i class="${i<task.fractionVisual.n?'on':''}"></i>`).join('')}</div>`;
  const locked=task.status==='wrong';
  choices=`<div class="knowledge-answers">${task.options.map((a,i)=>{const cls=locked?(i===task.correctIndex?'correct':i===task.wrongIndex?'wrong':'muted-answer'):'';const suffix=locked&&i===task.correctIndex?' <small>✓ richtig</small>':locked&&i===task.wrongIndex?' <small>deine Antwort</small>':'';return `<button type="button" class="knowledge-answer ${cls}" data-action="answer" data-index="${i}" ${locked?'disabled aria-disabled="true"':''}>${escape(a)}${suffix}</button>`;}).join('')}</div>`;
  if(locked){body+=`<div class="teacher-help error-review" role="status"><strong>Wissensbaustein</strong><p>${escape(task.explanation||`Die richtige Antwort ist ${task.answer}.`)}</p><small>Die Antworten bleiben gesperrt. Danach bekommst du eine neue Aufgabe zum selben Lernziel, statt die eingeblendete Lösung nachzuklicken.</small></div>`;choices+=reply('similar-task','Ähnliche Aufgabe →')+reply('knowledge','Für jetzt zum Wissensprofil');}
  else choices+=reply('world','„Wir denken später weiter darüber nach.“');
 }else{
  const aw=task.attributeAward,def=P.attributeMap[aw?.attributeId||task.attributeId]||attr,current=profile.attributes?.[def.id],levelUp=aw?.levels>0;
  text=`<p class="teacher-topic">${escape(domain.label)} · ${escape(task.topic||'verstanden')} · Stufe ${(task.tier??0)+1}/8</p><div class="spoken-question">Richtig beantwortet.</div>`;
  body=`<div class="learning-success" role="status"><span class="success-plus">+${aw?.development??2}</span><div><strong>${escape(def.label)}entwicklung</strong><p>${levelUp?`${escape(def.label)} steigt von ${aw.before} auf ${aw.after}.`:`Der Fortschrittsbalken von ${escape(def.label)} füllt sich weiter.`}</p>${current?`<div class="success-attribute-bar"><i style="width:${current.potential<=current.value?100:Math.min(100,current.progress/P.attributeCost(current.value)*100)}%"></i></div><small>${current.value>=current.potential?`Potenzial ${current.potential} erreicht`:`Wert ${current.value} · ${current.progress} / ${P.attributeCost(current.value)} bis zum nächsten Punkt · Maximum ${current.potential}`}</small>`:''}</div></div><p class="teacher-explanation">${escape(task.explanation||`Die Antwort lautet ${task.answer}.`)}</p>${task.earned?'<p class="dialog-gift">✦ Dein Wesen hat zusätzlich einen Fähigkeitspunkt erhalten.</p>':''}${bondLine?`<p class="teacher-note" role="status">${escape(bondLine)}${bondDelta>0?` Bindung +${bondDelta}.`:''}</p>`:''}`;
  choices=reply('next-task','Noch eine neue Aufgabe <small>1 Wissenspunkt</small>',`data-kind="${task.kind}"`,points<1)+reply('praise',`„Gut gemacht, ${escape(petName)}.“`)+reply('knowledge','Zum Wissensprofil');
 }
 const ks=knowledge?.domains?.[kind];
 return scene({npc,location,text,body,choices,footer:`<div class="conversation-footer"><span>◈ ${points} Wissenspunkte</span><span>${ks?`${ks.correct} richtig · ${ks.wrong} Lernfehler`:''}</span></div>`});
}
function resident({chapter,dialog,story}){
 const hasReply=dialog.step==='reply',result=dialog.result;
 return scene({npc:chapter.npc,location:`Kapitel ${chapter.id} · ${chapter.place}`,outdoors:true,text:escape(hasReply?result.response:chapter.dialog),body:hasReply&&result.gift?`<p class="dialog-gift">${escape(result.giftText)}</p><p class="gift-caption">Erhalten: ${escape(result.gift)} · +${result.reward} Wissenspunkte</p>`:'',choices:hasReply?reply('world','„Danke. Wir sehen uns wieder.“')+reply('resident-retry','„Darf ich noch etwas dazu sagen?“'):chapter.choices.map((c,i)=>reply('resident-choice',`„${escape(c.label)}“`,`data-index="${i}"`)).join('')});
}
function boss({chapter,story}){
 const resolved=!!story.resolved[chapter.id],trust=story.trust[chapter.id]>0;
 let text=resolved?`Der ${chapter.boss} lässt euch passieren. ${chapter.ending}`:trust?`Du erinnerst dich an das Gespräch mit ${window.KnowstersStory.residents[chapter.npc].name}. Vielleicht könnt ihr dem ${chapter.boss} zeigen, dass ihr seine Sorge verstanden habt.`:`Der ${chapter.boss} versperrt den Weg. Vielleicht weiß jemand in der Nähe, was ihn so aufbringt. Du kannst dich der Begegnung stellen oder erst mit den Bewohnern sprechen.`;
 const enemyId=window.KnowstersEnemies.bosses[chapter.id-1];
 const figure=enemyId==='mist'?`<img src="assets/nebelrufer.webp" alt="${escape(chapter.boss)}">`:`<div class="battle-actor regional-enemy encounter-creature" data-enemy="${enemyId}"><div class="combat-sprite" data-pose="idle" role="img" aria-label="${escape(chapter.boss)}"></div></div>`;
 return `<section class="story-encounter"><div class="encounter-figure">${figure}</div><div class="speech-panel"><div class="speaker-name">${escape(chapter.boss)}</div><p>${escape(text)}</p><div class="dialog-choices">${resolved?reply('chapter-gate','Den Weg fortsetzen →'):`${trust?reply('peaceful','Ruhig annähern und Verständnis zeigen'):''}${reply('new-battle','Der Begegnung im Kampf standhalten')}`}${reply('world','Zunächst zurück zum Weg')}</div></div></section>`;
}
function guide({dialog,story}){
 const c=window.KnowstersStory.current(story);const gifted=story.claimed.welcome;
 return scene({npc:'guide',location:'Lichtquell · am Forum',outdoors:true,text:escape(dialog.step==='reply'?dialog.result.response:`Fünf alte Wege führen durch diese Welt. Dein nächstes Ziel ist ${c.place}. Aber du musst nicht jede Schwierigkeit mit einem Kampf lösen. Frag die Bewohner, was sie beschäftigt. Rechnen, genaues Lesen und logisches Denken machen dich stärker – auch darin, Gerüchte zu erkennen und Streit ohne Gewalt zu lösen.`),body:dialog.step==='reply'?`${dialog.result.reward?`<p class="dialog-gift">+${dialog.result.reward} Wissenspunkte für deine ersten Besuche bei den Lehrpersonen.</p>`:''}${dialog.result.outfitUnlocked?`<p class="dialog-gift outfit-gift">◆ Neue Kleidung: ${escape(dialog.result.outfitName||'Outfit')} freigeschaltet.</p><p class="gift-caption">Du findest sie ab jetzt unter <strong>Stil</strong>.</p>`:''}`:'',choices:reply('journey-continue',`„Ich mache mich auf den Weg nach ${c.place}.“`)+(!gifted?reply('guide-gift','„Wie kann ich mich auf die Reise vorbereiten?“'):'')+reply('journal','„Erzähl mir von den fünf Wegen.“')+reply('world','„Ich bleibe noch etwas in Lichtquell.“')});
}
function traveler({dialog}){
 return scene({npc:'herbalist',location:'Eine Begegnung am Weg',outdoors:true,text:escape(dialog.step==='reply'?dialog.result.response:'Oh, ich habe dich gar nicht gehört. Ich habe mich verlaufen und bin ganz durcheinander. Darf ich mich kurz zu euch setzen?'),body:dialog.step==='reply'&&dialog.result.reward?`<p class="dialog-gift">Zum Dank erhältst du ${dialog.result.reward} Wissenspunkte.</p>`:'',choices:dialog.step==='reply'?reply('world','„Komm gut weiter.“'):reply('traveler-choice','„Natürlich. Atme erst einmal durch. Wohin möchtest du?“','data-index="0"')+reply('traveler-choice','„Ich kann dir den Weg nach Lichtquell zeigen.“','data-index="1"')+reply('world','„Heute kann ich nicht bleiben. Lichtquell liegt den Weg zurück.“')});
}
function journal(story){const S=window.KnowstersStory;return `<section class="journey-journal"><div class="screen-top"><div><div class="kicker">Eure gemeinsame Reise</div><h1>Die fünf Wege</h1></div><button class="secondary" data-action="world">Zur Welt</button></div>${S.chapters.map(c=>`<article class="chapter-entry ${story.completed[c.id]?'complete':c.id===story.chapter?'current':'future'}"><span class="chapter-number">${story.completed[c.id]?'✓':c.id}</span><div><small>${escape(c.place)}</small><h2>${escape(c.title)}</h2><p>${escape(story.completed[c.id]?c.ending:c.id<=story.chapter?c.objective:'Dieser Weg öffnet sich im Lauf eurer Reise.')}</p>${c.id<=story.chapter?`<span class="chapter-tasks">${story.met[c.id]?'✓':'○'} Bewohner getroffen · ${story.resolved[c.id]?'✓':'○'} Begegnung geklärt</span>`:''}</div></article>`).join('')}<section class="keepsakes"><h2>Erinnerungen von unterwegs</h2>${story.gifts.length?`<ul>${story.gifts.map(g=>`<li>${escape(g)}</li>`).join('')}</ul>`:'<p>Noch keine. Manche Menschen möchten dir etwas mitgeben, wenn ihr einander geholfen habt.</p>'}</section></section>`;}
window.KnowstersNarrative={portrait,reply,scene,teacher,resident,boss,guide,traveler,journal};
})();
