/* Five chapters, bounded encounter pacing and one-time social rewards. */
(()=>{'use strict';
const residents={
 professor:{name:'Professor Alwin',role:'Mathematiker',portrait:0,kind:'math',greeting:'Ah, Besuch! Zahlen erzählen Geschichten. Lass uns gemeinsam herausfinden, was dein kleiner Gefährte schon versteht.',about:'Wir beginnen mit einfachen Rechnungen. Wenn ihr sicherer werdet, kommen Klammern, Brüche und Prozente dazu. Bei kniffligen Fragen zeige ich dir den Weg.'},
 librarian:{name:'Mira',role:'Bibliothekarin',portrait:1,kind:'language',greeting:'Willkommen zwischen den Geschichten. Mit Worten können wir erklären, trösten – und manchmal sogar Streit beenden. Magst du eine Frage versuchen?',about:'Hier geht es um Wörter, Sätze und darum, genau zu verstehen, was jemand meint. Später schauen wir uns Texte und Argumente an.'},
 astronomer:{name:'Tara',role:'Forscherin im Denkturm',portrait:2,kind:'logic',greeting:'Siehst du das Muster in den Sternen? Nicht alles erkennt man auf den ersten Blick. Wir könnten zusammen ein Rätsel untersuchen.',about:'Wir suchen Muster, drehen Dinge im Kopf und prüfen, welche Schlüsse wirklich stimmen. Eine gute Frage hilft oft mehr als eine schnelle Antwort.'},
 herbalist:{name:'Nela',role:'Kräuterkundige',portrait:3},
 keeper:{name:'Jaro',role:'Brückenhüter',portrait:4},
 guide:{name:'Eno',role:'Reisebegleitung',portrait:5}
};
const teachers={math:'professor',language:'librarian',logic:'astronomer'};
const chapters=[
 {id:1,zone:'forest',title:'Die leisen Stimmen',place:'Flüsterwald',npc:'herbalist',boss:'Nebelrufer',intro:'Zwischen den Bäumen hört ihr eine leise Stimme. Nela sucht ihre verstreuten Kräuter. An der Ruine hat sich der Nebelrufer verkrochen.',objective:'Sprich mit Nela an der Quelle. Kläre danach die Begegnung an der Ruine.',dialog:'Seit die Wesen so unruhig sind, traue ich mich kaum noch an die Quelle. Gestern habe ich vor Schreck meinen Kräuterkorb fallen lassen. Im Spiegelnetz wird nur ein kurzer Ausschnitt geteilt. Viele halten das Wesen jetzt für gefährlich, ohne die ganze Geschichte zu kennen.',choices:[
  {label:'Das klingt beängstigend. Magst du erzählen, was passiert ist?',response:'Danke, dass du zuhörst. Der Nebelrufer hatte selbst Angst – er wollte mich wohl nur von seinem Versteck fernhalten.',trust:1},
  {label:'Wenn du möchtest, suchen wir die Kräuter gemeinsam.',response:'Gern. Zusammen traue ich mich wieder hin. Zwischen den Blättern findet ihr den Korb; der Nebelrufer hat ihn offenbar nur beiseitegeschoben.',trust:1},
  {label:'Ich muss erst weiter. Wir können später sprechen.',response:'Natürlich. Pass auf dich auf. Ich bleibe noch ein wenig hier.',trust:0}],gift:'Nelas Kräuterband',giftText:'Nela bindet dir ein kleines duftendes Kräuterband um. „Als Erinnerung: Du musst nicht alles allein schaffen.“',giftPoints:3,calm:'Du hältst Abstand und stellst Nelas Korb sichtbar ab. Der Nebelrufer erkennt, dass ihr ihm nichts wegnehmen wollt. Sein Zittern lässt nach.',ending:'Der Wald ist nicht völlig still geworden – aber zum ersten Mal hört ihr einander zu.'},
 {id:2,zone:'canyon',title:'Zwei Seiten einer Brücke',place:'Bernsteinschlucht',npc:'keeper',boss:'Brückenwächter',intro:'Eine alte Brücke verbindet zwei Siedlungen. Seit ein Geländer zerbrochen ist, beschuldigen sich beide Seiten gegenseitig.',objective:'Höre Jaro an. Finde einen Weg am aufgebrachten Brückenwächter vorbei.',dialog:'Die Leute auf der anderen Seite behaupten, ich hätte die Brücke absichtlich gesperrt. Dabei ist das Holz morsch. Ein Bild der Sperre wurde ohne meine Erklärung geteilt. Ich will doch nur verhindern, dass jemand abstürzt.',choices:[
  {label:'Du willst sie schützen, fühlst dich aber missverstanden?',response:'Genau. Vielleicht muss ich erklären, was kaputt ist, statt nur „gesperrt“ zu rufen. Danke, dass du nachfragst.',trust:1},
  {label:'Können wir gemeinsam zeigen, wo die Brücke unsicher ist?',response:'Das würde helfen. Ihr markiert die beschädigten Bretter. Nun verstehen die Wartenden, warum Jaro sie zurückhält.',trust:1},
  {label:'Ich schaue mich erst einmal selbst um.',response:'In Ordnung. Bleib bitte hinter den Markierungen – dort trägt das Holz noch.',trust:0}],gift:'Bernsteinanhänger',giftText:'Jaro schenkt dir einen kleinen Bernsteinanhänger von der Brücke. „Für jemanden, der beide Seiten sehen wollte.“',giftPoints:3,calm:'Du zeigst auf die markierten Bretter. Der Brückenwächter merkt, dass ihr seine Warnung verstanden habt, und lässt euch auf dem sicheren Weg passieren.',ending:'Nicht jede Sperre ist eine Drohung. Manchmal ist sie ein unbeholfener Versuch, andere zu schützen.'},
 {id:3,zone:'lake',title:'Was niemand sagt',place:'Spiegelsee',npc:'librarian',boss:'Spiegelschatten',intro:'Am See wartet Mira auf ein Wesen, das nicht mehr zu ihr zurückkommt. Im Wasser bewegen sich Schatten, obwohl kein Wind weht.',objective:'Sprich mit Mira am Ufer. Begegne dem Spiegelschatten.',dialog:'Ich dachte, wir hätten Spaß am Üben. Im Spiegelnetz sah alles so leicht aus. Dann habe ich Welle immer wieder verbessert. Jetzt versteckt sie sich. Ich weiß nicht, ob sie Ruhe braucht oder ob ich etwas falsch gemacht habe.',choices:[
  {label:'Vielleicht braucht sie erst einmal Ruhe. Du kannst ihr zeigen, dass du da bist.',response:'Ja. Ich muss nicht sofort eine Antwort verlangen. Mira setzt sich leise ans Ufer und lässt Platz neben sich frei.',trust:1},
  {label:'Du könntest sagen, was dir leid tut, ohne eine Antwort zu erwarten.',response:'Das möchte ich versuchen. „Es tut mir leid, dass ich dir keinen Raum gelassen habe“, sagt Mira in Richtung Wasser.',trust:1},
  {label:'Ich weiß gerade auch nicht, was helfen würde.',response:'Das ist ehrlich. Vielleicht ist es schon gut, dass wir nicht so tun, als wüssten wir alles.',trust:0}],gift:'Miras Lesezeichen',giftText:'Mira reicht dir ein Lesezeichen mit einer Welle darauf. „Manchmal braucht eine Geschichte eine Pause.“',giftPoints:4,calm:'Ihr wartet am Ufer, ohne nach dem Spiegelschatten zu greifen. Er kommt von selbst näher. Als er merkt, dass niemand ihn drängt, gibt er den Weg frei.',ending:'Nähe entsteht nicht dadurch, dass man sie einfordert. Am See habt ihr gelernt, Raum zu lassen.'},
 {id:4,zone:'pass',title:'Mut heißt auch Pause',place:'Windpass',npc:'astronomer',boss:'Sturmwächter',intro:'Der Weg wird steil. Tara wollte vor Einbruch der Dunkelheit den Pass überqueren, doch ihre Begleitung ist erschöpft.',objective:'Sprich mit Tara am Rastplatz. Kläre den Weg durch den Sturm.',dialog:'Ich habe allen versprochen, dass wir es heute schaffen. Wenn wir umkehren, denken sie bestimmt, ich sei schwach. Überall wird diese Mutprobe geteilt. Aber mein Gefährte kann kaum noch laufen.',choices:[
  {label:'Umzukehren kann mutig sein, wenn du damit auf euch aufpasst.',response:'Vielleicht muss ich niemandem etwas beweisen. Tara lockert ihren Rucksack und setzt sich neben ihren Gefährten.',trust:1},
  {label:'Lass uns zuerst einen windgeschützten Platz suchen und dann entscheiden.',response:'Ein guter nächster Schritt. Gemeinsam findet ihr Schutz hinter einer Felswand. Von dort ist der sichere Pfad viel besser zu sehen.',trust:1},
  {label:'Die Entscheidung liegt bei dir. Ich möchte dich nicht drängen.',response:'Danke. Ich werde meinen Gefährten nicht weiter antreiben. Wir brauchen einen Moment zum Nachdenken.',trust:0}],gift:'Taras Windkompass',giftText:'Tara überlässt dir ihren kleinen Windkompass. „Er zeigt eine Richtung – aber entscheiden müssen wir selbst.“',giftPoints:4,calm:'Du folgst dem geschützten Pfad und wartest, bis der Sturmwächter Platz macht. Ohne Gedränge und Hast kommt ihr aneinander vorbei.',ending:'Ihr habt den Pass nicht bezwungen. Ihr habt einen Weg gefunden, der für alle tragbar war.'},
 {id:5,zone:'sanctuary',title:'Das erste Erinnern',place:'Morgenhain',npc:'guide',boss:'Hüter des Nebels',intro:'Im Morgenhain treffen sich die alten Wege. Eno wartet am Kristall. Hier begann einst das Vergessen – und hier könnte etwas Neues beginnen.',objective:'Höre Eno zu. Begegne dem Hüter des Nebels und bringe die Reise zu Ende.',dialog:'Wir wollten immer klüger und stärker werden. Doch wir übten immer weniger, prüften kaum noch, was uns das Spiegelnetz zeigte, und hörten einander nicht mehr zu. Der Hüter bewahrt noch die Erinnerung daran – und die Angst, dass es wieder geschieht.',choices:[
  {label:'Wir können nicht versprechen, nie zu streiten. Aber wir können wieder zuhören.',response:'Ein ehrliches Versprechen. Eno nickt. Vielleicht braucht der Hüter keine perfekten Wesen, sondern welche, die es erneut versuchen.',trust:1},
  {label:'Lernen sollte uns helfen, einander besser zu verstehen, nicht nur zu gewinnen.',response:'Darum geht es. Wissen gibt Möglichkeiten; was wir damit tun, entscheiden wir gemeinsam.',trust:1},
  {label:'Ich muss darüber nachdenken. Ich habe nicht auf alles eine Antwort.',response:'Das musst du auch nicht. Fragen offenlassen zu können, ist ein Anfang.',trust:1}],gift:'Samen des Erinnerns',giftText:'Eno legt einen goldenen Samen in deine Hand. „Eine neue Geschichte wächst nicht an einem Tag.“',giftPoints:5,calm:'Du erzählst dem Hüter von Nela, Jaro, Mira und Tara. Nicht von Siegen, sondern von den Momenten, in denen ihr einander verstanden habt. Der Nebel löst sich langsam.',ending:'Die Wesen erinnern sich nicht plötzlich an alles. Aber sie beginnen wieder miteinander zu lernen. Und dein Gefährte bleibt an deiner Seite.'}
];
function create(){return{chapter:1,met:{},trust:{},resolved:{},completed:{},claimed:{},gifts:[],travel:0,nextEncounter:150,randomSeen:{},endingSeen:false};}
function hydrate(value){const s={...create(),...(value||{})};for(const key of ['met','trust','resolved','completed','claimed','randomSeen'])s[key]={...(s[key]||{})};s.gifts=Array.isArray(s.gifts)?s.gifts:[];s.chapter=Math.max(1,Math.min(5,Number(s.chapter)||1));return s;}
function current(s){return chapters[s.chapter-1];}
function forZone(zone){return chapters.find(c=>c.zone===zone)||null;}
function complete(s,id){if(s.met[id]&&s.resolved[id]){s.completed[id]=true;return true;}return false;}
function choose(s,id,index){const chapter=chapters[id-1],choice=chapter?.choices[index];if(!choice)return null;s.met[id]=true;s.trust[id]=Math.max(s.trust[id]||0,choice.trust);let reward=0,gift=null;if(choice.trust&&!s.claimed['npc-'+id]){s.claimed['npc-'+id]=true;s.gifts.push(chapter.gift);reward=chapter.giftPoints;gift=chapter.gift;}complete(s,id);return{response:choice.response,reward,gift,giftText:gift?chapter.giftText:null};}
function resolve(s,id,method){if(!chapters[id-1]||s.resolved[id])return false;s.resolved[id]=method;complete(s,id);return true;}
function advance(s,id){if(!s.completed[id])return false;if(id<5)s.chapter=Math.max(s.chapter,id+1);else s.endingSeen=true;return true;}
function resetTravel(s,rng=Math.random){s.travel=0;s.nextEncounter=110+rng()*85;}
function travel(s,zone,delta,safe,rng=Math.random){if(zone==='village'||!Number.isFinite(delta)||delta<=0)return null;s.travel+=Math.min(delta,5);if(safe||s.travel<s.nextEncounter)return null;resetTravel(s,rng);const roll=rng();return roll<.64?'attack':roll<.88?'traveler':'discovery';}
window.KnowstersStory={residents,teachers,chapters,create,hydrate,current,forZone,choose,resolve,complete,advance,travel,resetTravel};
})();
