const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'../v22'),ctx={window:{},Math};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root,'avatar.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(root,'avatar-editor.js'),'utf8'),ctx);
const A=ctx.window.KnowstersAvatar,E=ctx.window.KnowstersAvatarEditor;
const html=E.markup(A.defaults,{tops:[0],pants:[0]});
assert.ok(html.includes('avatar-editor-shell'));
assert.ok(html.includes('16 Frisuren'));
assert.ok(html.includes('10 Farben'));
assert.ok(html.includes('16 Gesichter'));
assert.ok(html.includes('data-field="hair"'));
assert.ok(html.includes('data-field="hairColor"'));
assert.ok(html.includes('data-field="face"'));
assert.ok(html.includes('data-field="top"'));
assert.ok(html.includes('disabled aria-disabled="true"'));
assert.equal((html.match(/data-field="hair"/g)||[]).length,16);
assert.equal((html.match(/data-field="hairColor"/g)||[]).length,10);
assert.equal((html.match(/data-field="face"/g)||[]).length,16);
assert.equal((html.match(/data-field="top"/g)||[]).length,16);
assert.equal((html.match(/data-field="pants"/g)||[]).length,16);
const wardrobeHtml=E.markup({...A.defaults,top:1},{tops:[0,1],pants:[0]},{mode:'wardrobe'});assert.ok(wardrobeHtml.includes('Charakter & Garderobe'));assert.ok(wardrobeHtml.includes('2 / 16 freigeschaltet'));assert.ok(wardrobeHtml.includes('data-action="wardrobe-save"'));assert.ok(!wardrobeHtml.includes('data-field="top" data-value="1" aria-pressed="true" aria-label="Layer Hoodie – noch nicht freigeschaltet" disabled'));
const randomized=E.randomize(A.defaults,{tops:[0],pants:[0]});assert.equal(randomized.top,0);assert.equal(randomized.pants,0);
console.log('PASS: character editor renders all avatar choices and keeps locked clothing unavailable at game start.');
